import pygame
from random import randint

screenx = 1280
screeny = 720
yOffset = 0

pygame.init()
screen = pygame.display.set_mode((screenx,screeny))
clock = pygame.time.Clock()
running = True #you better start running...

while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    screen.fill("black")

    fireButton = pygame.Rect(0,0,300,100)
    pygame.draw.rect(screen, (30,30,30), fireButton)

    pygame.display.flip()

    clock.tick(60)

pygame.quit()