import pygame
from random import randint

screenw = 1280
screenh = 720
yOffset = 0

pygame.init()

#Sounds for the gun :3
PlaySound = pygame.mixer.Sound.play
GunBlank = pygame.mixer.Sound("sfx/gun-blank.mp3")
GunShot = pygame.mixer.Sound("sfx/gun-shot.mp3")
GunSpin = pygame.mixer.Sound("sfx/gun-spin.mp3")


screen = pygame.display.set_mode((screenw,screenh))
MainSurface = pygame.Surface((screenw,screenh-yOffset))
clock = pygame.time.Clock()

running = True #you better start running...
startSpin = False

while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        elif event.type == pygame.KEYDOWN:
            if event.key == pygame.K_1:
                PlaySound(GunBlank)
            elif event.key == pygame.K_2:
                PlaySound(GunShot)
            elif event.key == pygame.K_3:
                PlaySound(GunSpin)
            elif event.key == pygame.K_SPACE:
                startSpin = True

    #revolver code

    #screen code
    screen.fill("black")

    pygame.draw.rect(MainSurface, (30,30,30), (0,0,300,100))
    screen.blit(MainSurface,(0,yOffset))

    pygame.display.flip()

    clock.tick(60)

pygame.quit()